### ISSUE TITLE
Alternative approach 

### ISSUE THREAD

**Issue by makasim** [BranchBit/AsyncDispatcherBundle#13]
I am working on an alternative solution https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/async_events.md
Super easy to use and works on many transports such as AMQP, STOMP, Amazon SQS, Doctrine DBAL and others

Could you please look at. The feedback would be much appreciated.

**Comment by whitewhidow** [comment]
My bundle simply moves the event processing to kernel.terminate, it is still running in the same php process. whereas your bundle delegates to an actual queue, so that it can be processed on a different machine, using different workers, these are 2 completely different approaches. and this is exactly the reason i created this bundle, to very easely integrate into existing event based code, and serve faster responses, without having to setup an actual queue.

**Comment by makasim** [comment]
Got your point. Few clarifications though. 

You could do send actual messages on the terminate event too.  So you do not waste your precise response time on it.

Also, there is a simple filesystem transport which is super easy to use (no extra deps). 

You reduce load on php-fpm nodes and the only thing you have to do is to run a consumer(s) processes in background

**Comment by whitewhidow** [comment]
yes, i understand,   dont get me wrong, i like your bundle (especially the well done docs). yours is just a heavier solution, for a heavier use-case. If i ever need real (with several workers, in different procersses) async handeling (other than sqs, i have a bundle for that), then i will give your bundle a go :)
